const products=[['MCB','⚡','₹180'],['Ceiling Fan','🌀','₹1,850'],['LED Bulb','💡','₹120'],['Copper Wire','〰️','₹680'],['Switch','🔘','₹75'],['Socket','🔌','₹95'],['Electrical Board','▦','₹420'],['Plug','🔋','₹65']];
const services=[['Electrician','⚡','Fan, wiring, switch & electrical repair'],['Plumber','🔧','Leakage, taps, pipes & fittings'],['Carpenter','🪚','Furniture, doors & wood work'],['AC Repair','❄️','AC service, gas & cooling issues'],['Mobile Repair','📱','Screen, battery & hardware repair'],['Laptop Repair','💻','Software and hardware support'],['Painter','🎨','Home and commercial painting'],['Bike Mechanic','🏍️','Bike service and repair']];
let cart=0;
const productGrid=document.getElementById('productGrid'); products.forEach((p,i)=>productGrid.innerHTML+=`<article class="product"><div class="product-img">${p[1]}</div><h3>${p[0]}</h3><p>Verified product • Fast delivery</p><div class="price"><b>${p[2]}</b><button class="add" onclick="addCart('${p[0]}')">+ Add</button></div></article>`);
const serviceGrid=document.getElementById('serviceGrid'); services.forEach(s=>serviceGrid.innerHTML+=`<article class="service"><div class="ico">${s[1]}</div><h3>${s[0]}</h3><p>${s[2]}</p><a class="book" href="#support" onclick="book('${s[0]}')">Book service →</a></article>`);
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function addCart(name){cart++;document.getElementById('cartCount').textContent=cart;toast(name+' added to cart');}
function showCart(){toast(cart?`${cart} item${cart>1?'s':''} in your cart`:'Your cart is empty')}
function loginDemo(){toast('Demo login — connect your backend here')}
function book(name){toast(name+' selected — booking flow ready')}
function openAI(){document.getElementById('aiPanel').classList.add('open')}
function closeAI(){document.getElementById('aiPanel').classList.remove('open')}
function ask(text){document.getElementById('aiInput').value=text;sendAI()}
function sendAI(){const input=document.getElementById('aiInput');const text=input.value.trim();if(!text)return;const chat=document.getElementById('chat');chat.innerHTML+=`<div class="bubble user">${text}</div>`;let r='I can help you with products, orders and services.';const t=text.toLowerCase();if(t.includes('fan'))r='I found Fan Repair. There are 3 available electricians. <b>Book Service</b> to continue.';else if(t.includes('order'))r='Your latest order is <b>OUT FOR DELIVERY</b>. Expected today.';else if(t.includes('mcb'))r='I found MCB products starting from <b>₹180</b>. Showing matching products above.';chat.innerHTML+=`<div class="bubble bot">${r}</div>`;input.value='';chat.scrollTop=chat.scrollHeight}
function voice(){if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){toast('Voice recognition is not supported in this browser');return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;const rec=new R();rec.lang='mr-IN';rec.onstart=()=>toast('🎙 Listening...');rec.onresult=e=>{document.getElementById('aiInput').value=e.results[0][0].transcript;sendAI()};rec.onerror=()=>toast('Voice input failed — please type instead');rec.start()}
